// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Logo       = require("./logo.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(Curry._4(Logo.createElement("REASON REACT"), /* [] */0, /* None */0, /* None */0, /* () */0), "index");

/*  Not a pure module */
