// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Logo       = require("./logo");
var Curry      = require("bs-platform/lib/js/curry");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe");

ReactDOMRe.renderToElementWithId(Curry._4(Logo.createElement("REASON REACT"), /* [] */0, /* None */0, /* None */0, /* () */0), "index");

/*  Not a pure module */
