// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry");
var React   = require("react");
var ReactRe = require("reason-react/lib/js/src/reactRe");

var componentDidMount = ReactRe.Component[0];

var componentWillUpdate = ReactRe.Component[1];

var componentDidUpdate = ReactRe.Component[2];

var componentWillReceiveProps = ReactRe.Component[3];

var componentWillUnmount = ReactRe.Component[4];

var getInstanceVars = ReactRe.Component[5];

var jsPropsToReasonProps = ReactRe.Component[6];

var getInitialState = ReactRe.Component[7];

var name = "Page";

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* None */0;
}

function render(param) {
  return React.createElement("div", {
              onClick: Curry._1(param[/* updater */2], handleClick)
            }, param[/* props */1][/* message */0]);
}

var Page_008 = /* Stateful */ReactRe.Component[8];

var Page_009 = /* JsProps */ReactRe.Component[9];

var Page_010 = /* InstanceVars */ReactRe.Component[10];

var Page = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  /* getInitialState */getInitialState,
  Page_008,
  Page_009,
  Page_010,
  /* name */name,
  /* handleClick */handleClick,
  /* render */render
];

var include = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include[1];

function createElement(message) {
  return Curry._1(wrapProps, /* record */[/* message */message]);
}

var comp = include[0];

exports.Page          = Page;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* include Not a pure module */
