// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Page       = require("./page");
var Curry      = require("bs-platform/lib/js/curry");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe");

ReactDOMRe.renderToElementWithId(Curry._4(Page.createElement("Hello!"), /* [] */0, /* None */0, /* None */0, /* () */0), "index");

/*  Not a pure module */
