// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var ReactRe    = require("reason-react/lib/js/src/reactRe");
var Js_boolean = require("bs-platform/lib/js/js_boolean");
var MyBanner   = require("../../../../src/interop/myBanner");

function createElement(show, message) {
  var partial_arg = {
    show: Js_boolean.to_js_boolean(show),
    message: message
  };
  var partial_arg$1 = MyBanner;
  return function (param, param$1, param$2, param$3) {
    return ReactRe.wrapPropsShamelessly(partial_arg$1, partial_arg, param, param$1, param$2, param$3);
  };
}

exports.createElement = createElement;
/* ReactRe Not a pure module */
