// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var MyBanner    = require("../../../../src/interop/myBanner");

function make(show, message, children) {
  return ReasonReact.wrapJsComponentForReason(MyBanner, {
              show: Js_boolean.to_js_boolean(show),
              message: message
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
