// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Curry        = require("bs-platform/lib/js/curry.js");
var React        = require("react");
var ReactRe      = require("reason-react/lib/js/src/reactRe.js");
var MyBannerRe   = require("./myBannerRe.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var include = ReactRe.Component[/* JsProps */9];

var componentDidMount = include[0];

var componentWillUpdate = include[1];

var componentDidUpdate = include[2];

var componentWillReceiveProps = include[3];

var componentWillUnmount = include[4];

var getInstanceVars = include[5];

var getInitialState = include[6];

var name = "PageReason";

function render(param) {
  var props = param[/* props */1];
  var match = props[/* extraGreeting */1];
  var greeting = match ? match[0] : "How are you?";
  return React.createElement("div", undefined, MyBannerRe.createElement(/* true */1, props[/* message */0] + (" " + greeting))(/* [] */0, /* None */0, /* None */0, /* () */0));
}

var jsPropsToReasonProps = /* Some */[function (jsProps) {
    return /* record */[
            /* message */jsProps.message,
            /* extraGreeting */Js_primitive.null_undefined_to_opt(jsProps.extraGreeting)
          ];
  }];

var PageReason = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* getInitialState */getInitialState,
  /* name */name,
  /* render */render,
  /* jsPropsToReasonProps */jsPropsToReasonProps
];

var include$1 = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include$1[1];

function createElement(message, extraGreeting) {
  return Curry._1(wrapProps, /* record */[
              /* message */message,
              /* extraGreeting */extraGreeting
            ]);
}

var comp = include$1[0];

exports.PageReason    = PageReason;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* include Not a pure module */
